services:
  payload:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        NPM_REGISTRY: ${NPM_REGISTRY:-https://registry.npmmirror.com}
        # APT_MIRROR: ${APT_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn/debian}
        # APT_SECURITY_MIRROR: ${APT_SECURITY_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn/debian-security}
    image: payload
    container_name: payload
    restart: unless-stopped
    command: sh -c "pnpm ${APP_CMD:-dev}"
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/home/node/.pnpm-store
      - ~/.aws:/home/node/.aws
    environment:
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    command: postgres -c config_file=/var/lib/postgresql/postgresql.conf
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  pgdata:
    external: true
    name: xc2f_pgdata
  pnpm_store:
  node_modules:
